services:
  postgres:
    image: postgres:17.4-alpine
    container_name: cloud-pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: video_process_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.4.3-alpine
    container_name: video_process_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: