apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-apps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark-apps

---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: test-spark # TODO: change the name
  namespace: spark-apps
spec:
  type: Python
  mode: cluster
  image: csit5970-test-spark:latest
  imagePullPolicy: Never # only for local image
  pythonVersion: "3"
  mainApplicationFile: "local:///app/test-spark.py"
  restartPolicy:
    type: Never
  sparkVersion: 3.5.5
  driver:
    labels:
      version: 3.5.5
    cores: 1
    memory: 512m
    serviceAccount: spark
    env:
      - name: KAFKA_BOOTSTRAP_SERVER
        value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  executor:
    labels:
      version: 3.5.5
    instances: 1
    cores: 1
    memory: 512m
    env:
      - name: KAFKA_BOOTSTRAP_SERVER
        value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
