// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: frame.proto

package framepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The message format for sending frames
type FrameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobID         string                 `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	FrameID       int32                  `protobuf:"varint,2,opt,name=frameID,proto3" json:"frameID,omitempty"`
	FrameData     []byte                 `protobuf:"bytes,3,opt,name=frameData,proto3" json:"frameData,omitempty"` // binary image data, in JPEG format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameMessage) Reset() {
	*x = FrameMessage{}
	mi := &file_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameMessage) ProtoMessage() {}

func (x *FrameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameMessage.ProtoReflect.Descriptor instead.
func (*FrameMessage) Descriptor() ([]byte, []int) {
	return file_frame_proto_rawDescGZIP(), []int{0}
}

func (x *FrameMessage) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *FrameMessage) GetFrameID() int32 {
	if x != nil {
		return x.FrameID
	}
	return 0
}

func (x *FrameMessage) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

var File_frame_proto protoreflect.FileDescriptor

const file_frame_proto_rawDesc = "" +
	"\n" +
	"\vframe.proto\x12\x10csit5970.backend\"\\\n" +
	"\fFrameMessage\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x18\n" +
	"\aframeID\x18\x02 \x01(\x05R\aframeID\x12\x1c\n" +
	"\tframeData\x18\x03 \x01(\fR\tframeDataB\n" +
	"Z\b/framepbb\x06proto3"

var (
	file_frame_proto_rawDescOnce sync.Once
	file_frame_proto_rawDescData []byte
)

func file_frame_proto_rawDescGZIP() []byte {
	file_frame_proto_rawDescOnce.Do(func() {
		file_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)))
	})
	return file_frame_proto_rawDescData
}

var file_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_frame_proto_goTypes = []any{
	(*FrameMessage)(nil), // 0: csit5970.backend.FrameMessage
}
var file_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_frame_proto_init() }
func file_frame_proto_init() {
	if File_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frame_proto_rawDesc), len(file_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frame_proto_goTypes,
		DependencyIndexes: file_frame_proto_depIdxs,
		MessageInfos:      file_frame_proto_msgTypes,
	}.Build()
	File_frame_proto = out.File
	file_frame_proto_goTypes = nil
	file_frame_proto_depIdxs = nil
}
